pr:
- master

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  ContainerRegistry: 'hubblenews-gcr'

stages:
  - stage: Build_front_ressources
    displayName: Build front ressources
    jobs:
    - job: Build
      displayName: 'Build Image'
      steps:
        - task: Npm@1
          displayName: 'npm install'
          inputs:
            command: install
            workingDir: '$(System.DefaultWorkingDirectory)/front'
        - script: |
            set -e
            cd front/
            sudo npm install -g @ionic/cli
            ionic capacitor sync
            ls
        - task: Docker@2
          displayName: 'Build image'
          inputs:
            command: 'buildAndPush'
            containerRegistry: '$(ContainerRegistry)'
            Dockerfile: './config/nginx/Dockerfile'
            buildContext: './'
            repository: eu.gcr.io/nginx