### INGRESS
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hubblenews
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hubblenews-ip
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: nginx
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: api
          servicePort: 80
      - path: /api/*
        backend:
          serviceName: api
          servicePort: 80

---
### SERVICE - API
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: api
  type: NodePort

---
### SERVICE - NGINX
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
  type: NodePort

---
### VOLUMES
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hubblenews-files
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    fsType: ext4
    pdName: disk-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hubblenews-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi

---
### STATEFULSET - API
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-statefulset
spec:
  selector:
    matchLabels:
      app: api
  serviceName: "api-service"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: API_IMAGE
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hubblevolume
          mountPath: /home/images
        env:
        - name: API_PORT
          value: "8000"
      volumes:
      - name: hubblevolume
        persistentVolumeClaim:
          claimName: hubblenews-claim

---
### DEPLOYEMENT - NGINX
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: NGINX_IMAGE