apiVersion: v1
kind: Pod
metadata:
  name: back
  labels:
    role: developer
    app: back
spec:
  containers:
  - name: api
    image: nginx
    ports:
     - containerPort:80
  - name: database
    image: mysql
    ports:
     - containerPort:3306
volumes:
  - name: back-storage
    emptyDir: {}