apiVersion: v1
kind: Service
metadata:
  name: back-service  
  labels:
    app: back
spec:
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: back
  type: NodePort